app:
  opendata:
    host: api.eia.gov
    key: ihcUijUMAXNltgdtrK7fagcb78mYGwIQw4gRg2ZM
  vehicle-metadata:
    hummer: 210
    lyriq: 100
    silverado: 200
    bolt: 66
management:
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    db:
      enabled: true
server:
  port: 8080
spring:
  data:
    jpa:
      repositories:
         bootstrap-mode: default
  datasource:
    url: jdbc:h2:mem:appdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
